# Use Node.js as the base image
FROM node:20-alpine

# Install build tools and Python
RUN apk add --no-cache make gcc g++ python3

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application files
COPY . .

# Expose the backend port
EXPOSE 3000

# Start the backend server
CMD ["nodemon", "src/app.js"]
